# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bernard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
