# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bernard', '0002_auto_20170209_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scptask',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bernard.Job'),
        ),
        migrations.AlterField(
            model_name='sshtask',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bernard.Job'),
        ),
    ]
