# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bernard', '0004_schedulelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'failed'), (1, 'success'), (2, 'error'), (3, 'running')]),
        ),
    ]
